#!/usr/bin/env python
import sys
import subprocess
_DEFAULT = 0
_EXTENSION_MAP = {'pdf':'evince',
                  '/': 'nautilus',
                  'mp4': 'vlc',
                  _DEFAULT:'emacsclient'}
_DEBUG = False

def parse_extension(file_name):
    if file_name[-1] == '/':
        return '/'
    return file_name.split('.')[-1]

if __name__=='__main__':
    doc_key = parse_extension(sys.argv[1])
    try:
        cmd = [_EXTENSION_MAP[doc_key]]
    except KeyError:
        cmd = [_EXTENSION_MAP[_DEFAULT]]
    # NOTE: Currently passing all remaining arguments
    cmd.extend(sys.argv[1:])
    if not _DEBUG:
        p = subprocess.Popen(cmd, shell=False)
    else:
        print cmd
